import org.code.neighborhood.*;

public class FramePainter extends PainterPlus {

/* ------------------ paintFrame ------------------
   * 📄 Paints outer edge and only goes foward or turns left or right.
   * --------------------------------------------------
   */
  
public void paintFrame(String color){
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
turnRight();
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move();
paint(color);
move();
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
turnRight();
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move();
paint(color);
move();
paint(color);
move(); 
paint(color);
turnRight();
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move();
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
move(); 
paint(color);
 }
}